# https://taskfile.dev

version: "3"

interval: 500ms

tasks:
  tailwind-watch:
    aliases:
      - tw
    cmds:
      - pnpx tailwindcss -i ./input.css -o ./assets/tailwind.css --watch
    silent: true

  create-manifest:
    cmds:
      - mgen --cwd "{{.USER_WORKING_DIR}}" --alias hrt --file "{{.USER_WORKING_DIR}}\dist\bundle\msi\html-to-rsx-ui_0.1.0_x64_en-US.msi" --bin html-to-rsx-ui.exe
    desc: Runs create manifest for current crate.

  scoop-install:
    cmds:
      - scoop install "$HOME\scoop\buckets\local\html-to-rsx-ui.json"
    desc: Installs the app with Scoop
